import {
  AchievementCategory,
  AchievementRarity,
} from "@/src/api/entities/Achievement";

/**
 * Master list of all achievements.
 * These are upserted on first use via ensureAchievementsSeeded().
 *
 * Design principle: mix quick wins (GenZ dopamine hits) with
 * deep long-term goals (Elder pride, Griot prestige).
 */
export const ACHIEVEMENT_SEEDS = [
  // ── BUILDER ──────────────────────────────────────────────
  {
    key: "first_blood",
    name: "First Root",
    description: "Add your very first family member.",
    icon: "🌱",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.COMMON,
    xpReward: 50,
    progressTarget: 1,
    progressField: "personsAdded",
  },
  {
    key: "family_of_5",
    name: "Growing Tree",
    description: "Add 5 people to the family database.",
    icon: "🌿",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.COMMON,
    xpReward: 75,
    progressTarget: 5,
    progressField: "personsAdded",
  },
  {
    key: "family_of_20",
    name: "Full Household",
    description: "Add 20 people to the database.",
    icon: "🏡",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 150,
    progressTarget: 20,
    progressField: "personsAdded",
  },
  {
    key: "family_of_50",
    name: "Extended Family",
    description: "Add 50 people. The ancestors are proud.",
    icon: "🌳",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.RARE,
    xpReward: 300,
    progressTarget: 50,
    progressField: "personsAdded",
  },
  {
    key: "family_of_100",
    name: "The Village",
    description: "100 people in the database. You built a village!",
    icon: "🏘️",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.EPIC,
    xpReward: 600,
    progressTarget: 100,
    progressField: "personsAdded",
  },
  {
    key: "first_link",
    name: "First Bond",
    description: "Link two people with a relationship.",
    icon: "🔗",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.COMMON,
    xpReward: 30,
    progressTarget: 1,
    progressField: "relationshipsAdded",
  },
  {
    key: "matchmaker",
    name: "Matchmaker",
    description: "Record 10 relationships.",
    icon: "💍",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 120,
    progressTarget: 10,
    progressField: "relationshipsAdded",
  },
  {
    key: "web_weaver",
    name: "Web Weaver",
    description: "Record 50 relationships — you hold the family together.",
    icon: "🕸️",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.RARE,
    xpReward: 400,
    progressTarget: 50,
    progressField: "relationshipsAdded",
  },
  {
    key: "first_tree",
    name: "Tree Planter",
    description: "Create your first family tree.",
    icon: "🌲",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.COMMON,
    xpReward: 60,
    progressTarget: 1,
    progressField: "treesCreated",
  },
  {
    key: "three_trees",
    name: "Forest Keeper",
    description: "Create 3 family trees.",
    icon: "🌲🌲🌲",
    category: AchievementCategory.BUILDER,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 200,
    progressTarget: 3,
    progressField: "treesCreated",
  },

  // ── HISTORIAN ─────────────────────────────────────────────
  {
    key: "first_story",
    name: "The Storyteller",
    description: "Write your first biography.",
    icon: "📖",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.COMMON,
    xpReward: 75,
    progressTarget: 1,
    progressField: "biographiesWritten",
  },
  {
    key: "five_stories",
    name: "Library of Lives",
    description: "Write 5 biographies.",
    icon: "📚",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 200,
    progressTarget: 5,
    progressField: "biographiesWritten",
  },
  {
    key: "first_oral",
    name: "Voice of the Elders",
    description: "Record your first oral history or tradition.",
    icon: "🎙️",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.COMMON,
    xpReward: 100,
    progressTarget: 1,
    progressField: "oralHistoriesWritten",
  },
  {
    key: "five_oral",
    name: "Griot Rising",
    description: "Record 5 oral histories. You carry the ancestors' voices.",
    icon: "🪘",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.RARE,
    xpReward: 350,
    progressTarget: 5,
    progressField: "oralHistoriesWritten",
  },
  {
    key: "first_photo",
    name: "Memory Keeper",
    description: "Add a photo to a family member.",
    icon: "📷",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.COMMON,
    xpReward: 40,
    progressTarget: 1,
    progressField: "photosAdded",
  },
  {
    key: "ten_photos",
    name: "Family Album",
    description: "Add 10 photos. Every face has a story.",
    icon: "🖼️",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 150,
    progressTarget: 10,
    progressField: "photosAdded",
  },
  {
    key: "ceremony_recorder",
    name: "Ceremony Recorder",
    description:
      "Record a lobola, initiation, or naming ceremony as a life event.",
    icon: "🥁",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 120,
    progressTarget: 1,
    progressField: "eventsAdded",
  },
  {
    key: "twenty_events",
    name: "Chronicler",
    description: "Record 20 life events.",
    icon: "📜",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.RARE,
    xpReward: 300,
    progressTarget: 20,
    progressField: "eventsAdded",
  },
  {
    key: "first_clan",
    name: "Clan Founder",
    description: "Register a clan with its totem.",
    icon: "🦁",
    category: AchievementCategory.HISTORIAN,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 100,
    progressTarget: 1,
    progressField: "clansCreated",
  },

  // ── CONNECTOR ─────────────────────────────────────────────
  {
    key: "first_merge",
    name: "Bridge Builder",
    description: "Submit your first merge request.",
    icon: "🌉",
    category: AchievementCategory.CONNECTOR,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 150,
    progressTarget: 1,
    progressField: "mergeRequestsSubmitted",
  },
  {
    key: "approved_merge",
    name: "Family Reunion",
    description: "Have a merge request approved — families united!",
    icon: "🤝",
    category: AchievementCategory.CONNECTOR,
    rarity: AchievementRarity.RARE,
    xpReward: 400,
    progressTarget: 1,
    progressField: "mergesApproved",
  },
  {
    key: "three_merges",
    name: "Peacemaker",
    description: "Get 3 merges approved. You are the glue of your lineage.",
    icon: "☮️",
    category: AchievementCategory.CONNECTOR,
    rarity: AchievementRarity.EPIC,
    xpReward: 800,
    progressTarget: 3,
    progressField: "mergesApproved",
  },

  // ── STREAK ────────────────────────────────────────────────
  {
    key: "streak_3",
    name: "3-Day Devotee",
    description: "Log in and contribute 3 days in a row.",
    icon: "🔥",
    category: AchievementCategory.STREAK,
    rarity: AchievementRarity.COMMON,
    xpReward: 60,
    progressTarget: 3,
    progressField: "currentStreak",
  },
  {
    key: "streak_7",
    name: "Week of Remembrance",
    description: "7-day contribution streak — the elders are watching!",
    icon: "🔥🔥",
    category: AchievementCategory.STREAK,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 200,
    progressTarget: 7,
    progressField: "currentStreak",
  },
  {
    key: "streak_30",
    name: "The Devoted",
    description: "30-day streak. You are a true keeper of family memory.",
    icon: "⚡",
    category: AchievementCategory.STREAK,
    rarity: AchievementRarity.EPIC,
    xpReward: 750,
    progressTarget: 30,
    progressField: "currentStreak",
  },

  // ── MILESTONE (Level-based) ───────────────────────────────
  {
    key: "level_3",
    name: "Branch Builder",
    description: "Reach Level 3 — Branch Builder.",
    icon: "⭐",
    category: AchievementCategory.MILESTONE,
    rarity: AchievementRarity.COMMON,
    xpReward: 0,
    progressTarget: 3,
    progressField: "level",
  },
  {
    key: "level_5",
    name: "Elder Scribe",
    description: "Reach Level 5 — Elder Scribe.",
    icon: "🌟",
    category: AchievementCategory.MILESTONE,
    rarity: AchievementRarity.RARE,
    xpReward: 0,
    progressTarget: 5,
    progressField: "level",
  },
  {
    key: "level_8",
    name: "Griot Master",
    description: "Reach the highest level — Griot Master. Legendary.",
    icon: "🏆",
    category: AchievementCategory.MILESTONE,
    rarity: AchievementRarity.LEGENDARY,
    xpReward: 0,
    progressTarget: 8,
    progressField: "level",
  },

  // ── SPECIAL ───────────────────────────────────────────────
  {
    key: "both_sides",
    name: "Both Sides Now",
    description:
      "Link family members from both maternal and paternal lineages.",
    icon: "⚖️",
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 250,
    progressTarget: null,
    progressField: null,
  },
  {
    key: "diaspora_mapper",
    name: "Diaspora Mapper",
    description:
      "Add a family member with origin in one country who migrated to another.",
    icon: "✈️",
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.UNCOMMON,
    xpReward: 200,
    progressTarget: null,
    progressField: null,
  },
  {
    key: "century_lineage",
    name: "Century Lineage",
    description: "Add a person born before 1924 — 100+ year family memory!",
    icon: "🕰️",
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.RARE,
    xpReward: 300,
    progressTarget: null,
    progressField: null,
  },
  {
    key: "four_generations",
    name: "Four Generations",
    description:
      "Build a tree with at least 4 generations (great-grandparent to great-grandchild).",
    icon: "👴👩‍👧‍👦👶",
    category: AchievementCategory.SPECIAL,
    rarity: AchievementRarity.EPIC,
    xpReward: 500,
    progressTarget: null,
    progressField: null,
  },
];
