import { QuestType } from "@/src/api/entities/Quest";
import { XPEventType } from "@/src/api/entities/XPEvent";

export const QUEST_SEEDS = [
  // ── ONBOARDING (one-time) ─────────────────────────────────
  {
    key: "onboard_1_person",
    title: "Meet the Family",
    description: "Add your first family member to get started.",
    icon: "👶",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.ADD_PERSON,
    targetCount: 1,
    xpReward: 50,
  },
  {
    key: "onboard_1_rel",
    title: "First Connection",
    description: "Link two people with a relationship.",
    icon: "🔗",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.ADD_RELATIONSHIP,
    targetCount: 1,
    xpReward: 30,
  },
  {
    key: "onboard_1_tree",
    title: "Plant Your Tree",
    description: "Create your first family tree.",
    icon: "🌱",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.CREATE_TREE,
    targetCount: 1,
    xpReward: 60,
  },
  {
    key: "onboard_1_event",
    title: "Record a Moment",
    description: "Add a life event (birth, wedding, initiation…).",
    icon: "📅",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.ADD_LIFE_EVENT,
    targetCount: 1,
    xpReward: 40,
  },
  {
    key: "onboard_1_photo",
    title: "Put a Face to the Name",
    description: "Add a photo to a family member's profile.",
    icon: "📷",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.ADD_PHOTO,
    targetCount: 1,
    xpReward: 40,
  },
  {
    key: "onboard_1_bio",
    title: "Tell Their Story",
    description: "Write a biography for a family member.",
    icon: "✍️",
    type: QuestType.ONBOARDING,
    trackedEvent: XPEventType.WRITE_BIOGRAPHY,
    targetCount: 1,
    xpReward: 75,
  },

  // ── DAILY ─────────────────────────────────────────────────
  {
    key: "daily_add_person",
    title: "Daily: Add a Family Member",
    description: "Add at least one person today.",
    icon: "👤",
    type: QuestType.DAILY,
    trackedEvent: XPEventType.ADD_PERSON,
    targetCount: 1,
    xpReward: 30,
  },
  {
    key: "daily_add_rel",
    title: "Daily: Make a Connection",
    description: "Link two people with a relationship today.",
    icon: "💞",
    type: QuestType.DAILY,
    trackedEvent: XPEventType.ADD_RELATIONSHIP,
    targetCount: 1,
    xpReward: 25,
  },
  {
    key: "daily_add_event",
    title: "Daily: Record History",
    description: "Add a life event today.",
    icon: "📖",
    type: QuestType.DAILY,
    trackedEvent: XPEventType.ADD_LIFE_EVENT,
    targetCount: 1,
    xpReward: 25,
  },

  // ── WEEKLY ────────────────────────────────────────────────
  {
    key: "weekly_5_persons",
    title: "Weekly: Family Expansion",
    description: "Add 5 people this week.",
    icon: "🌿",
    type: QuestType.WEEKLY,
    trackedEvent: XPEventType.ADD_PERSON,
    targetCount: 5,
    xpReward: 150,
  },
  {
    key: "weekly_5_rels",
    title: "Weekly: Web of Kinship",
    description: "Record 5 relationships this week.",
    icon: "🕸️",
    type: QuestType.WEEKLY,
    trackedEvent: XPEventType.ADD_RELATIONSHIP,
    targetCount: 5,
    xpReward: 100,
  },
  {
    key: "weekly_write_story",
    title: "Weekly: The Oral Tradition",
    description: "Write 2 oral histories or biographies this week.",
    icon: "🎙️",
    type: QuestType.WEEKLY,
    trackedEvent: XPEventType.WRITE_ORAL_HISTORY,
    targetCount: 2,
    xpReward: 200,
  },
  {
    key: "weekly_clan",
    title: "Weekly: Know Your Roots",
    description: "Add or update a clan record this week.",
    icon: "🦁",
    type: QuestType.WEEKLY,
    trackedEvent: XPEventType.CREATE_CLAN,
    targetCount: 1,
    xpReward: 120,
  },
  {
    key: "weekly_merge",
    title: "Weekly: Family Reunion Seeker",
    description: "Submit a merge request this week.",
    icon: "🌉",
    type: QuestType.WEEKLY,
    trackedEvent: XPEventType.SUBMIT_MERGE_REQUEST,
    targetCount: 1,
    xpReward: 175,
  },

  // ── DISCOVERY ─────────────────────────────────────────────
  {
    key: "discovery_diaspora",
    title: "Trace the Diaspora",
    description: "Add a family member who migrated to a different country.",
    icon: "✈️",
    type: QuestType.DISCOVERY,
    trackedEvent: XPEventType.ADD_PERSON,
    targetCount: 1,
    xpReward: 200,
  },
  {
    key: "discovery_elder",
    title: "Find the Oldest Root",
    description: "Add a person born before 1950.",
    icon: "👴",
    type: QuestType.DISCOVERY,
    trackedEvent: XPEventType.ADD_PERSON,
    targetCount: 1,
    xpReward: 150,
  },
  {
    key: "discovery_oral",
    title: "The Griot's Challenge",
    description: "Record 3 oral histories — carry the ancestors' voices.",
    icon: "🪘",
    type: QuestType.DISCOVERY,
    trackedEvent: XPEventType.WRITE_ORAL_HISTORY,
    targetCount: 3,
    xpReward: 300,
  },
];
